-- Generated from src/data/products.ts and src/data/blog.ts.
-- Review the result before executing it in Supabase SQL Editor.
begin;

insert into public.products (
  id, name, slug, sku, reference, brand, category, short_description, description_html,
  purchase_price_xof, regular_price_xof, sale_price_xof, stock_quantity, low_stock_threshold, status,
  primary_image, gallery_images, attributes, colors, faq,
  value_story_title, value_story_text, provenance_summary, warranty_summary, delivery_summary, stock_policy
) values
(
  'prod-tissot-le-locle-20th', 'Tissot Le Locle 20th Anniversary 39,3 mm', 'tissot-le-locle-20th-anniversary-t006-407-11-033-03', 'T006.407.11.033.03', 'T006.407.11.033.03', 'Tissot',
  'montres', 'Automatique. Acier inoxydable 316L. Glace saphir. Réserve de marche jusqu''à 80 heures.', '<p>Cette Tissot Le Locle associe un mouvement automatique Powermatic 80 à un boîtier et un bracelet en acier inoxydable 316L. Son cadran argenté et son fond transparent donnent à la mécanique une présence classique, précise et durable. Une pièce pensée pour accompagner les jours qui comptent, puis les suivants.</p>',
  0, 550000, null, 3, 2, 'published',
  '/assets/products/tissot-le-locle.jpg', '[{"url":"/assets/products/tissot-le-locle.jpg","alt":"Tissot Le Locle 20th Anniversary 39,3 mm, référence T006.407.11.033.03, vue de face sur fond ivoire.","isPrimary":true,"type":"face"},{"url":"/assets/products/le-locle-angle.jpg","alt":"Tissot Le Locle 20th Anniversary 39,3 mm, référence T006.407.11.033.03, vue en trois-quarts montrant le boîtier et le bracelet.","type":"trois-quarts"},{"url":"/assets/products/le-locle-caseback.jpg","alt":"Tissot Le Locle 20th Anniversary 39,3 mm, référence T006.407.11.033.03, détail du fond transparent.","type":"fond"}]'::jsonb, '{"modele":"Tissot Le Locle 20th Anniversary 39,3 mm","reference":"T006.407.11.033.03","diametre":"39,3 mm","boitier":"Acier inoxydable 316L","verre":"Glace saphir résistante aux rayures","fondDeBoite":"Transparent","mouvement":"Automatique","reserveDeMarche":"Jusqu''à 80 heures","bracelet":"Interchangeable à ouverture facile","etancheite":"Jusqu''à 3 bar (30 m)","cadran":"Argenté guilloché","fabrication":"Suisse (Swiss Made)"}'::jsonb, '[]'::jsonb, '[{"question":"Cette pièce est-elle disponible ?","answer":"Le statut affiché est mis à jour depuis le catalogue. Il est contrôlé à nouveau avant la validation de votre commande."},{"question":"Puis-je demander un conseil avant d''ajouter cette montre au panier ?","answer":"Oui. Indiquez la référence T006.407.11.033.03 à HERITAGE pour échanger au sujet de cette pièce."},{"question":"Où retrouver les conditions applicables à cette pièce ?","answer":"Les informations de provenance, de garantie, de livraison et de retour sont accessibles depuis les blocs ci-dessus lorsqu''elles sont publiées."}]'::jsonb,
  'La constance d''une mécanique qui sait se faire remarquer avec retenue.', 'Cette Tissot Le Locle associe un mouvement automatique Powermatic 80 à un boîtier et un bracelet en acier inoxydable 316L. Son cadran argenté et son fond transparent donnent à la mécanique une présence classique, précise et durable. Une pièce pensée pour accompagner les jours qui comptent, puis les suivants.', null, null, null, 'standard'
),
(
  'prod-tissot-pr516-011', 'Tissot PR516 Chronographe 40 mm', 'tissot-pr516-40mm-t149-417-11-011-00', 'T149.417.11.011.00', 'T149.417.11.011.00', 'Tissot',
  'montres', 'Quartz. Acier inoxydable 316L avec revêtement PVD. Glace saphir avec traitement antireflet.', '<p>Inspirée des tableaux de bord et de l''héritage automobile de 1968, la PR516 associe un cadran chronographe lisible à une boîte en acier 316L et une lunette tachymétrique soignée. Une pièce rythmée pour mesurer chaque étape avec calme.</p>',
  0, 330000, null, 4, 2, 'published',
  '/assets/products/tissot-pr516-white.jpg', '[{"url":"/assets/products/tissot-pr516-white.jpg","alt":"Tissot PR516 40 mm, référence T149.417.11.011.00, vue de face sur fond ivoire.","isPrimary":true,"type":"face"}]'::jsonb, '{"modele":"Tissot PR516 40 mm","reference":"T149.417.11.011.00","diametre":"40 mm","boitier":"Acier inoxydable 316L avec revêtement PVD","verre":"Glace saphir résistante aux rayures avec traitement antireflet","fondDeBoite":"Gravé","mouvement":"Quartz","bracelet":"Interchangeable à ouverture facile","etancheite":"Jusqu''à 10 bar (100 m)","cadran":"Argenté blanc avec sous-compteurs noirs","fabrication":"Suisse (Swiss Made)"}'::jsonb, '[]'::jsonb, '[{"question":"Cette pièce est-elle disponible ?","answer":"Le statut affiché est mis à jour depuis le catalogue. Il est contrôlé à nouveau avant la validation de votre commande."},{"question":"Puis-je demander un conseil avant d''ajouter cette montre au panier ?","answer":"Oui. Indiquez la référence T149.417.11.011.00 à HERITAGE pour échanger au sujet de cette pièce."}]'::jsonb,
  'L''esprit chronographe historique revisité avec une précision contemporaine.', 'Inspirée des tableaux de bord et de l''héritage automobile de 1968, la PR516 associe un cadran chronographe lisible à une boîte en acier 316L et une lunette tachymétrique soignée. Une pièce rythmée pour mesurer chaque étape avec calme.', null, null, null, 'standard'
),
(
  'prod-tissot-pr516-041', 'Tissot PR516 Chronographe Cadran Bleu 40 mm', 'tissot-pr516-cadran-bleu-40mm-t149-417-11-041-00', 'T149.417.11.041.00', 'T149.417.11.041.00', 'Tissot',
  'montres', 'Quartz. Acier inoxydable 316L. Glace saphir avec traitement antireflet.', '<p>Cette déclinaison au cadran bleu profond capte la lumière avec nuance. Son boîtier en acier 316L et son bracelet interchangeable garantissent une robustesse sans faille au quotidien.</p>',
  0, 330000, null, 2, 2, 'published',
  '/assets/products/tissot-pr516-blue.jpg', '[{"url":"/assets/products/tissot-pr516-blue.jpg","alt":"Tissot PR516 40 mm, référence T149.417.11.041.00, vue de face sur fond ivoire.","isPrimary":true,"type":"face"}]'::jsonb, '{"modele":"Tissot PR516 40 mm","reference":"T149.417.11.041.00","diametre":"40 mm","boitier":"Acier inoxydable 316L","verre":"Glace saphir avec traitement antireflet","fondDeBoite":"Gravé","mouvement":"Quartz","bracelet":"Interchangeable à ouverture facile","etancheite":"Jusqu''à 10 bar (100 m)","cadran":"Bleu soleillé","fabrication":"Suisse (Swiss Made)"}'::jsonb, '[]'::jsonb, '[{"question":"Cette pièce est-elle disponible ?","answer":"Le statut affiché est mis à jour depuis le catalogue. Il est contrôlé à nouveau avant la validation de votre commande."},{"question":"Puis-je demander un conseil avant d''ajouter cette montre au panier ?","answer":"Oui. Indiquez la référence T149.417.11.041.00 à HERITAGE pour échanger au sujet de cette pièce."}]'::jsonb,
  'La profondeur d''un cadran bleu soleillé pour un style sportif épuré.', 'Cette déclinaison au cadran bleu profond capte la lumière avec nuance. Son boîtier en acier 316L et son bracelet interchangeable garantissent une robustesse sans faille au quotidien.', null, null, null, 'standard'
),
(
  'prod-tissot-pr100-011', 'Tissot PR 100 40 mm', 'tissot-pr-100-40mm-t150-410-16-011-00', 'T150.410.16.011.00', 'T150.410.16.011.00', 'Tissot',
  'montres', 'Quartz. Acier inoxydable 316L. Glace saphir. Bracelet interchangeable à ouverture facile.', '<p>La Tissot PR 100 est une référence d''élégance sobre. Des lignes nettes, un cadran épuré et une glace saphir inrayable pour une présence naturelle et durable.</p>',
  0, 198000, null, 5, 2, 'published',
  '/assets/products/tissot-pr100.jpg', '[{"url":"/assets/products/tissot-pr100.jpg","alt":"Tissot PR 100 40 mm, référence T150.410.16.011.00, vue de face sur fond ivoire.","isPrimary":true,"type":"face"}]'::jsonb, '{"modele":"Tissot PR 100 40 mm","reference":"T150.410.16.011.00","diametre":"40 mm","boitier":"Acier inoxydable 316L","verre":"Glace saphir résistante aux rayures","mouvement":"Quartz","bracelet":"Interchangeable à ouverture facile","etancheite":"Jusqu''à 10 bar (100 m)","cadran":"Argenté","fabrication":"Suisse (Swiss Made)"}'::jsonb, '[]'::jsonb, '[{"question":"Cette pièce est-elle disponible ?","answer":"Le statut affiché est mis à jour depuis le catalogue. Il est contrôlé à nouveau avant la validation de votre commande."},{"question":"Puis-je demander un conseil avant d''ajouter cette montre au panier ?","answer":"Oui. Indiquez la référence T150.410.16.011.00 à HERITAGE pour échanger au sujet de cette pièce."}]'::jsonb,
  'La simplicité pure d''une montre quotidienne à la fiabilité éprouvée.', 'La Tissot PR 100 est une référence d''élégance sobre. Des lignes nettes, un cadran épuré et une glace saphir inrayable pour une présence naturelle et durable.', null, null, null, 'standard'
),
(
  'prod-tissot-seastar-1000-black', 'Tissot Seastar 1000 40 mm', 'tissot-seastar-1000-40mm-t120-410-33-051-00', 'T120.410.33.051.00', 'T120.410.33.051.00', 'Tissot',
  'montres', 'Quartz. Acier inoxydable 316L avec revêtement PVD. Étanchéité jusqu''à 30 bar.', '<p>Conçue pour défier les éléments aquatiques jusqu''à 300 mètres, la Seastar 1000 conserve une finesse et une élégance qui conviennent aussi bien aux tenues habillées qu''aux aventures sportives.</p>',
  0, 290000, null, 3, 2, 'published',
  '/assets/products/tissot-seastar-black.jpg', '[{"url":"/assets/products/tissot-seastar-black.jpg","alt":"Tissot Seastar 1000 40 mm, référence T120.410.33.051.00, vue de face sur fond ivoire.","isPrimary":true,"type":"face"}]'::jsonb, '{"modele":"Tissot Seastar 1000 40 mm","reference":"T120.410.33.051.00","diametre":"40 mm","boitier":"Acier inoxydable 316L avec revêtement PVD","verre":"Glace saphir résistante aux rayures avec traitement antireflet","fondDeBoite":"Vissé","mouvement":"Quartz","bracelet":"Interchangeable à ouverture facile","etancheite":"Jusqu''à 30 bar (300 m / 1000 ft)","cadran":"Noir avec index luminescents","fabrication":"Suisse (Swiss Made)"}'::jsonb, '[]'::jsonb, '[{"question":"Cette pièce est-elle disponible ?","answer":"Le statut affiché est mis à jour depuis le catalogue. Il est contrôlé à nouveau avant la validation de votre commande."},{"question":"Puis-je demander un conseil avant d''ajouter cette montre au panier ?","answer":"Oui. Indiquez la référence T120.410.33.051.00 à HERITAGE pour échanger au sujet de cette pièce."}]'::jsonb,
  'L''étanchéité professionnelle dans un format 40 mm aux finitions nobles.', 'Conçue pour défier les éléments aquatiques jusqu''à 300 mètres, la Seastar 1000 conserve une finesse et une élégance qui conviennent aussi bien aux tenues habillées qu''aux aventures sportives.', null, null, null, 'standard'
),
(
  'prod-tissot-seastar-1000-red', 'Tissot Seastar 1000 Cadran Rouge Dégradé 40 mm', 'tissot-seastar-1000-cadran-rouge-t1204103342100', 'T1204103342100', 'T1204103342100', 'Tissot',
  'montres', 'Quartz. Cadran rouge dégradé. Acier inoxydable 316L avec revêtement PVD. Étanchéité jusqu''à 30 bar.', '<p>Ce modèle arbore un cadran soleillé dégradé remarquable qui attire le regard sans ostentation. Alliant robustesse 30 bar et esthétique racée, c''est une pièce d''une grande personnalité.</p>',
  0, 285000, null, 1, 2, 'published',
  '/assets/products/tissot-seastar-red.jpg', '[{"url":"/assets/products/tissot-seastar-red.jpg","alt":"Tissot Seastar 1000 40 mm, référence T1204103342100, vue de face sur fond ivoire.","isPrimary":true,"type":"face"}]'::jsonb, '{"modele":"Tissot Seastar 1000 40 mm","reference":"T1204103342100","diametre":"40 mm","boitier":"Acier inoxydable 316L avec revêtement PVD","verre":"Glace saphir résistante aux rayures avec traitement antireflet","fondDeBoite":"Vissé","mouvement":"Quartz","bracelet":"Interchangeable à ouverture facile","etancheite":"Jusqu''à 30 bar (300 m / 1000 ft)","cadran":"Rouge dégradé","fabrication":"Suisse (Swiss Made)"}'::jsonb, '[]'::jsonb, '[{"question":"Cette pièce est-elle disponible ?","answer":"Le statut affiché est mis à jour depuis le catalogue. Il est contrôlé à nouveau avant la validation de votre commande."},{"question":"Puis-je demander un conseil avant d''ajouter cette montre au panier ?","answer":"Oui. Indiquez la référence T1204103342100 à HERITAGE pour échanger au sujet de cette pièce."}]'::jsonb,
  'Un tempérament audacieux sublimé par un dégradé rouge et noir singulier.', 'Ce modèle arbore un cadran soleillé dégradé remarquable qui attire le regard sans ostentation. Alliant robustesse 30 bar et esthétique racée, c''est une pièce d''une grande personnalité.', null, null, null, 'standard'
),
(
  'prod-tissot-chemin-des-tourelles-gold', 'Tissot Chemin Des Tourelles 42 mm', 'tissot-chemin-des-tourelles-42mm-t139-407-22-038-00', 'T139.407.22.038.00', 'T139.407.22.038.00', 'Tissot',
  'montres', 'Automatique. Acier inoxydable 316L avec revêtement PVD. Glace saphir. Réserve de marche jusqu''à 80 heures.', '<p>Portant le nom de la rue où Tissot a établi ses ateliers en 1907, cette montre incarne le savoir-faire helvétique le plus noble. Finitions bicolores, calibre automatique Powermatic 80 et fond transparent révélant le mouvement.</p>',
  0, 460000, null, 2, 2, 'published',
  '/assets/products/tissot-chemin-gold.jpg', '[{"url":"/assets/products/tissot-chemin-gold.jpg","alt":"Tissot Chemin Des Tourelles 42 mm, référence T139.407.22.038.00, vue de face sur fond ivoire.","isPrimary":true,"type":"face"}]'::jsonb, '{"modele":"Tissot Chemin Des Tourelles 42 mm","reference":"T139.407.22.038.00","diametre":"42 mm","boitier":"Acier inoxydable 316L avec revêtement PVD","verre":"Glace saphir résistante aux rayures avec traitement antireflet","fondDeBoite":"Transparent","mouvement":"Automatique","reserveDeMarche":"Jusqu''à 80 heures","bracelet":"Interchangeable à ouverture facile","etancheite":"Jusqu''à 5 bar (50 m)","cadran":"Argenté soleillé bicolore","fabrication":"Suisse (Swiss Made)"}'::jsonb, '[]'::jsonb, '[{"question":"Cette pièce est-elle disponible ?","answer":"Le statut affiché est mis à jour depuis le catalogue. Il est contrôlé à nouveau avant la validation de votre commande."},{"question":"Puis-je demander un conseil avant d''ajouter cette montre au panier ?","answer":"Oui. Indiquez la référence T139.407.22.038.00 à HERITAGE pour échanger au sujet de cette pièce."}]'::jsonb,
  'La signature historique du berceau horloger de Tissot.', 'Portant le nom de la rue où Tissot a établi ses ateliers en 1907, cette montre incarne le savoir-faire helvétique le plus noble. Finitions bicolores, calibre automatique Powermatic 80 et fond transparent révélant le mouvement.', null, null, null, 'standard'
),
(
  'prod-tissot-chemin-des-tourelles-blue', 'Tissot Chemin Des Tourelles Cadran Bleu Foncé 42 mm', 'tissot-chemin-des-tourelles-bleu-t139-407-11-048-00', 'T139.407.11.048.00', 'T139.407.11.048.00', 'Tissot',
  'montres', 'Automatique. Cadran bleu foncé. Acier inoxydable 316L. Glace saphir. Réserve de marche jusqu''à 80 heures.', '<p>Une allure intemporelle portée par un cadran bleu nuit profond et un boîtier en acier inoxydable 316L satiné et poli. La mécanique Powermatic 80 assure plus de 3 jours d''autonomie sans compromis de précision.</p>',
  0, 460000, null, 3, 2, 'published',
  '/assets/products/tissot-chemin-blue.jpg', '[{"url":"/assets/products/tissot-chemin-blue.jpg","alt":"Tissot Chemin Des Tourelles 42 mm, référence T139.407.11.048.00, vue de face sur fond ivoire.","isPrimary":true,"type":"face"}]'::jsonb, '{"modele":"Tissot Chemin Des Tourelles 42 mm","reference":"T139.407.11.048.00","diametre":"42 mm","boitier":"Acier inoxydable 316L","verre":"Glace saphir résistante aux rayures avec traitement antireflet","fondDeBoite":"Transparent","mouvement":"Automatique","reserveDeMarche":"Jusqu''à 80 heures","bracelet":"Interchangeable à ouverture facile","etancheite":"Jusqu''à 5 bar (50 m)","cadran":"Bleu foncé soleillé","fabrication":"Suisse (Swiss Made)"}'::jsonb, '[]'::jsonb, '[{"question":"Cette pièce est-elle disponible ?","answer":"Le statut affiché est mis à jour depuis le catalogue. Il est contrôlé à nouveau avant la validation de votre commande."},{"question":"Puis-je demander un conseil avant d''ajouter cette montre au panier ?","answer":"Oui. Indiquez la référence T139.407.11.048.00 à HERITAGE pour échanger au sujet de cette pièce."}]'::jsonb,
  'L''élégance souveraine du bleu nuit combinée au Powermatic 80.', 'Une allure intemporelle portée par un cadran bleu nuit profond et un boîtier en acier inoxydable 316L satiné et poli. La mécanique Powermatic 80 assure plus de 3 jours d''autonomie sans compromis de précision.', null, null, null, 'standard'
)
on conflict (id) do update set
  name = excluded.name, slug = excluded.slug, sku = excluded.sku, reference = excluded.reference,
  brand = excluded.brand, category = excluded.category, short_description = excluded.short_description,
  description_html = excluded.description_html, regular_price_xof = excluded.regular_price_xof,
  stock_quantity = excluded.stock_quantity, status = excluded.status, primary_image = excluded.primary_image,
  gallery_images = excluded.gallery_images, attributes = excluded.attributes, colors = excluded.colors,
  faq = excluded.faq, value_story_title = excluded.value_story_title, value_story_text = excluded.value_story_text,
  provenance_summary = null, warranty_summary = null, delivery_summary = null, stock_policy = excluded.stock_policy;

insert into public.blog_posts (
  title, slug, excerpt, content_html, cover_image, status, published_at, category, tags, related_product_ids
) values
(
  'Automatique ou Quartz : Bien choisir son garde-temps', 'choisir-montre-automatique-ou-quartz', 'La distinction entre montre mécanique automatique et calibre à quartz ne se résume pas à une question de prix. Elle touche au rapport que vous entretenez avec l''objet, à son autonomie et à sa vocation de transmission patrimoniale.', '<h2>Le mouvement automatique : l''énergie vivante du geste</h2><p>Une montre automatique tire son énergie des mouvements naturels de votre poignet. Une masse oscillante (le rotor), visible au travers du fond transparent de pièces d''exception comme la Tissot Le Locle, remonte en continu le ressort de barillet.</p><p>Avec des calibres modernes comme le Powermatic 80, la réserve de marche atteint 80 heures. Vous pouvez déposer la montre le vendredi soir et la retrouver le lundi matin parfaitement à l''heure sans intervention.</p><p>Choisir une automatique, c''est choisir un objet vivant et intemporel. Elle ne nécessite aucune pile : entretenue tous les cinq ans, elle traverse les décennies et se transmet naturellement de génération en génération.</p><h2>Le calibre à quartz : la précision absolue et l''immédiateté</h2><p>Une montre à quartz utilise la vibration régulière d''un cristal de quartz sous l''impulsion d''une pile électrique pour cadencer le temps avec une précision rigoureuse de quelques secondes par an.</p><p>C''est le choix privilégié pour une montre sportive, un chronographe d''intervention ou une pièce active. Vous la posez, vous la reprenez après plusieurs semaines, et la trotteuse bat la mesure avec une ponctualité infaillible.</p><p>La pile se remplace simplement tous les deux à trois ans lors d''un contrôle d''étanchéité réalisé par nos soins à Abidjan.</p><h2>Quel choix pour votre prochaine acquisition ?</h2><p>Si votre souhait est d''acquérir une création noble marquant un accomplissement personnel ou destinée à être léguée, le mouvement automatique offre une poésie et une dimension artisanale uniques.</p><p>Si vous cherchez un instrument quotidien, robuste et immédiatement opérationnel en toutes circonstances à Abidjan, un calibre quartz suisse de manufacture répondra à votre exigence.</p>', '/assets/products/le-locle-caseback.jpg',
  'published', now(), 'Horlogerie', '[]'::jsonb, '["prod-tissot-le-locle-20th"]'::jsonb
),
(
  'L''Art du Sillage : Bien porter son parfum sous le climat d''Abidjan', 'art-du-parfum-sublimer-son-sillage-a-abidjan', 'Sous le climat chaud et humide d''Abidjan, les fragrances réagissent avec intensité. Découvrez les secrets pour choisir entre Eau de Parfum et Extrait, et faire rayonner votre signature olfactive avec subtilité.', '<h2>Comprendre l''évaporation des essences sous la chaleur</h2><p>La température corporelle et l''hygrométrie accélèrent la diffusion des molécules odorantes de tête (agrumes, bergamote, notes ozoniques). Celles-ci s''expriment avec éclat mais s''estompent plus rapidement.</p><p>Pour conserver une aura sophistiquée tout au long de la journée, privilégiez des compositions dotées d''un cœur floral noble (jasmin, néroli, iris) et d''un fond boisé ou ambré (oud, santal, fève tonka, musc blanc) qui se fixent idéalement sur l''épiderme.</p><h2>Eau de Parfum vs Extrait : la juste concentration</h2><p>L''Eau de Parfum offre un équilibre parfait entre fraîcheur d''ouverture et rémanence au bureau ou lors de vos rendez-vous d''affaires au Plateau ou à Cocody.</p><p>Pour les grandes réceptions ou les dîners mondains, les Extraits de Parfum et les élixirs rares délivrent une concentration supérieure à 25%, libérant une signature envoûtante sans jamais être entêtante.</p><h2>Les zones de diffusion stratégiques</h2><p>Vaporisez sur les points de pulsation : l''intérieur des poignets, les creux des clavicules et derrière les oreilles. Pour une élégance absolue sans altérer vos étoffes précieuses, un nuage léger au revers de votre veste assure un sillage mémorable.</p>', '/assets/products/seastar-wrist.jpg',
  'published', now(), 'Haute Parfumerie', '[]'::jsonb, '[]'::jsonb
),
(
  'Lunettes Solaires de Créateur : Allier Haute Protection UV et Allure', 'guide-lunettes-de-soleil-createur-protection-et-style', 'Au-delà d''un accessoire de style incontournable, une monture de luxe solaire à Abidjan est un bouclier indispensable contre le rayonnement solaire intense. Repères de style et d''ergonomie.', '<h2>Indice de protection et verres polarisés</h2><p>À proximité de la lagune Ébrié et du littoral de Grand-Bassam ou Assinie, la réverbération de la lumière est particulièrement forte. Des verres solaires de catégorie 3 dotés d''un filtre polarisant éliminent les reflets parasites et améliorent les contrastes sans assombrir la vue.</p><p>Toutes nos montures solaires répondent aux normes strictes de filtration 100% UVA et UVB pour préserver votre santé visuelle.</p><h2>Morphologie et architecture des montures</h2><p>Les visages ovales profitent d''une liberté totale de formes, des modèles pilotes aviateur aux silhouettes géométriques contemporaines.</p><p>Pour un visage rond ou carré, les formes pantos, hexagonales ou rectangulaires adoucissent les traits et structurent le port de tête avec une élégance naturelle.</p><p>L''acétate de cellulose de haute densité et le titane poli garantissent une légèreté exceptionnelle au porter, même pendant les heures les plus chaudes.</p><h2>L''accord parfait entre lunettes, montre et accessoires</h2><p>Harmonisez les métaux : une monture aux accents dorés ou or rose dialoguera idéalement avec le boîtier bicolore de votre garde-temps. Pour un look contemporain et épuré, l''acétate noir profond s''associe avec un bracelet en acier 316L.</p>', '/assets/products/pr516-chronograph.jpg',
  'published', now(), 'Lunetterie de Luxe', '[]'::jsonb, '[]'::jsonb
)
on conflict (slug) do update set
  title = excluded.title, excerpt = excluded.excerpt, content_html = excluded.content_html,
  cover_image = excluded.cover_image, status = excluded.status, published_at = excluded.published_at,
  category = excluded.category, tags = excluded.tags, related_product_ids = excluded.related_product_ids;

-- Existing contact details are migrated from the former Contact page. Social
-- links and footer promises remain empty until they are validated in the CMS.
update public.site_settings set
  business_name = 'HERITAGE',
  email = 'contact@heritage-abidjan.ci',
  phone = '+225 07 07 18 15 60',
  whatsapp_phone = '+225 07 07 18 15 60',
  address = 'Maison HERITAGE · Yopougon, Abidjan, Côte d''Ivoire',
  hours = 'Lundi au Samedi : 09h00 – 19h00 (GMT)',
  social_links = '{}'::jsonb,
  footer_notices = '[]'::jsonb
where id = true;

commit;
